import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
}

// JavaCPP ships native FFmpeg libs per-platform under a classifier; each CI job packages
// for the OS it's running on, so only that OS's classifier needs to be on the classpath.
val javacppPlatform = run {
    val osName = System.getProperty("os.name").lowercase()
    val osArch = System.getProperty("os.arch").lowercase()
    when {
        osName.contains("win") -> "windows-x86_64"
        osName.contains("mac") -> if (osArch.contains("aarch64") || osArch.contains("arm")) "macosx-arm64" else "macosx-x86_64"
        else -> "linux-x86_64"
    }
}

// ── Bundled Google OAuth client ──────────────────────────────────────────────
// Desktop-app OAuth clients have no real secret (Google documents this), so the
// release build bakes a default client in. Values come from the environment (CI
// secrets / local shell), never from a tracked file. Users can still override them
// with ~/.config/wren/oauth.json.
val googleClientId = providers.environmentVariable("WREN_GOOGLE_CLIENT_ID").orElse("")
val googleClientSecret = providers.environmentVariable("WREN_GOOGLE_CLIENT_SECRET").orElse("")
val buildConfigDir = layout.buildDirectory.dir("generated/buildconfig")

val generateBuildConfig by tasks.registering {
    inputs.property("googleClientId", googleClientId)
    inputs.property("googleClientSecret", googleClientSecret)
    outputs.dir(buildConfigDir)
    doLast {
        val file = buildConfigDir.get().file("BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :desktop:generateBuildConfig — do not edit.
            |object BuildConfig {
            |    const val GOOGLE_CLIENT_ID: String = "${googleClientId.get()}"
            |    const val GOOGLE_CLIENT_SECRET: String = "${googleClientSecret.get()}"
            |}
            |""".trimMargin()
        )
    }
}

sourceSets.main { kotlin.srcDir(buildConfigDir) }
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach { dependsOn(generateBuildConfig) }

dependencies {
    implementation(project(":shared"))
    implementation(compose.desktop.currentOs)
    implementation(compose.material)
    implementation(compose.materialIconsExtended)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.bytedeco:javacv:1.5.11")
    implementation("org.bytedeco:ffmpeg:7.1-1.5.11")
    implementation("org.bytedeco:ffmpeg:7.1-1.5.11:$javacppPlatform")
    // JavaFX WebView for embedded SoundCloud login
    val jfxClassifier = when {
        javacppPlatform.contains("linux") -> "linux"
        javacppPlatform.contains("macosx-arm") -> "mac-aarch64"
        javacppPlatform.contains("macosx") -> "mac"
        javacppPlatform.contains("windows") -> "win"
        else -> "linux"
    }
    implementation("org.openjfx:javafx-base:21.0.4:$jfxClassifier")
    implementation("org.openjfx:javafx-web:21.0.4:$jfxClassifier")
    implementation("org.openjfx:javafx-controls:21.0.4:$jfxClassifier")
    implementation("org.openjfx:javafx-graphics:21.0.4:$jfxClassifier")
    implementation("org.openjfx:javafx-media:21.0.4:$jfxClassifier")
    implementation("org.openjfx:javafx-swing:21.0.4:$jfxClassifier")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(21)
}

// The real release version. Compose Desktop's Dmg validation requires MAJOR > 0, so macOS
// gets its own jpackage-internal version below; the public artifact still gets renamed to
// this version in CI. Deb/Msi have no such restriction and use it directly.
val appVersion = "0.6.0"

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Deb, TargetFormat.Rpm, TargetFormat.Msi, TargetFormat.Dmg)
            packageName = "wren"
            packageVersion = appVersion
            // javafx-web (SoundCloud login WebView) needs jdk.jsobject + jdk.xml.dom in the
            // jlinked runtime; the rest come from `./gradlew :desktop:suggestRuntimeModules`.
            modules("java.instrument", "java.management", "java.net.http", "jdk.jfr", "jdk.jsobject", "jdk.unsupported", "jdk.xml.dom")
            linux {
                iconFile.set(project.file("wren.png"))
            }
            macOS {
                // Both the app-image bundler (createDistributable) and the Dmg bundler
                // enforce jpackage's MAJOR > 0 rule, so both need overriding here — never
                // shown to users. CI renames the produced .dmg to the real appVersion.
                packageVersion = "1.0.0"
                dmgPackageVersion = "1.0.0"
            }
        }
    }
}
